### ISSUE TITLE
How to trigger event when the selection is made

### ISSUE THREAD

**Issue by kaleto** [scottdarby/Stylish-Select#21]
Can anybody help me to trigger some event when the selection has been made.
I.e. if I have a stylish country select box, when I choose a country to redirect to some internal page. It's very important to keep the keyboard shortcuts as arrow navigation.

**Comment by xxorax** [comment]
However, the event is not called outside jQuery namespace, other libraries cannot handle it, like prototype :
Event.observe('id_of_select', 'change', function () { 'never called'; });
